# Generated by Django 5.2.4 on 2025-07-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='about_images/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('experience_years', models.PositiveIntegerField()),
                ('vulnerabilities_found', models.PositiveIntegerField()),
                ('certifications', models.CharField(help_text='Comma-separated list of certifications.', max_length=300)),
                ('ctf_teams', models.CharField(help_text='Comma-separated list of CTF teams.', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('about_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='core.aboutinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('github_link', models.URLField()),
                ('tags', models.ManyToManyField(related_name='projects', to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the title.', unique=True)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('read_time', models.PositiveIntegerField(help_text='Estimated reading time in minutes.')),
                ('tags', models.ManyToManyField(related_name='blog_posts', to='core.tag')),
            ],
        ),
    ]
